version: "3.3"

services:
  reverse-proxy:
    image: traefik:latest
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './traefik.toml:/traefik.toml'
      - "./letsencrypt:/letsencrypt"
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.docker.network: proxy
        traefik.http.services.reverse-proxy.loadbalancer.server.port: '8080'
        traefik.http.routers.reverse-proxy.service: api@internal
      placement:
        constraints:
        - node.role==manager
    networks:
      - proxy

networks:
  proxy:
    external: true # docker network create -d overlay proxy
